"""Shared task and execution-support models."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from voltron.shared.enums import AgentName, TaskType


@dataclass
class TaskRequest:
    """User task request accepted by the orchestrator."""

    task_id: str
    description: str
    task_type: TaskType = TaskType.MANIPULATION
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class Subtask:
    """A single executable unit assigned to one specialized agent."""

    subtask_id: str
    agent: AgentName
    action: str
    target: dict[str, Any] = field(default_factory=dict)
    parameters: dict[str, Any] = field(default_factory=dict)
    context: dict[str, Any] = field(default_factory=dict)
    plan_revision: int = 0
    execution_id: str | None = None
    replaces_execution_id: str | None = None

    @property
    def runtime_id(self) -> str:
        """Stable identity for runtime state, distinct from plan-local ordering."""

        return self.execution_id or self.subtask_id


@dataclass
class Plan:
    """Ordered subtask plan generated by the planner."""

    subtasks: list[Subtask]
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class LocalSkillSelection:
    """Normalized local skill selection output used inside embodied agents."""

    skill_id: str
    confidence: float = 0.0
    reason: str = ""
    source: str = "local_selector"
    fallback_skill_candidates: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
